spring.application.name=art-shop-api

# URL do banco
spring.datasource.url=jdbc:postgresql://localhost:5432/vbartshop_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Configurações do Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=vbartshop-secret-key-super-forte-e-segura-123456